name: Buildandpush

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: bash command
      run: cd /home/runner/work/FluentBlob/FluentBlob/src/FluentBlob.Core/bin/Release/
    - name: bash list
      run: ls
